name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.0
  flutter: "3.32.7"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^14.0.0
  logging: ^1.2.0
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_in_app_messaging: ^0.9.0+4
  firebase_messaging: ^16.0.4
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
