name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  

dependencies:
  crypto: ^3.0.6
  dart_frog: ^1.2.4
  dart_frog_auth: ^1.2.2
  dart_glicko2:
    path: ../packages/dart_glicko2
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  postgres: ^3.5.9
  stormberry: ^0.18.0
  talker: ^5.0.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.10.1
  dart_frog_cli: ^1.2.5
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^5.1.0
