name: push_notification_service
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  overlay_support: ^2.1.0
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1

dev_dependencies:
  build_runner: ^2.4.7
  coverage: ^1.6.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.17.10
